import { supabase } from '../lib/supabase.js';
import { unwrap } from './client.js';

export function listOnboardingCases() {
  return supabase
    .from('onboarding_cases')
    .select('*')
    .order('created_at', { ascending: false })
    .then(unwrap);
}

export function getOnboardingCase(id) {
  return supabase.from('onboarding_cases').select('*').eq('id', id).single().then(unwrap);
}

/** Every status here is a real, persisted transition — no step is faked. */
export function updateOnboardingStatus(id, status) {
  return supabase.from('onboarding_cases').update({ status }).eq('id', id).select('*').single().then(unwrap);
}

/** Creates the employee record and marks the case complete. employee_code is
    generated by the database (employee_code_seq) unless overridden. */
export async function createEmployee(onboardingCase, { joiningDate, department, designation } = {}) {
  const employee = await supabase
    .from('employees')
    .insert({
      onboarding_case_id: onboardingCase.id,
      full_name: onboardingCase.candidate_name,
      email: onboardingCase.candidate_email,
      department: department || onboardingCase.department,
      designation: designation || onboardingCase.designation,
      joining_date: joiningDate || onboardingCase.joining_date,
    })
    .select('*')
    .single()
    .then(unwrap);

  await updateOnboardingStatus(onboardingCase.id, 'employee_created');
  return employee;
}
